name: Continuous Delivery
on:
  push:
    branches:
      - main # ou qualquer outra branch que você deseja monitorar
      
jobs:
 deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - NAME: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
          with:
            name: projetozipado.zip
            path: |
              '**.py'
              README.md
              